DROP TABLE IF EXISTS EMPLEADO;  
CREATE TABLE EMPLEADO (  
Empleado_code INT AUTO_INCREMENT  PRIMARY KEY,  
Empleado_first_name VARCHAR(50) NOT NULL,  
Empleado_last_name VARCHAR(50) NOT NULL,  
Empleo VARCHAR(50) NOT NULL,  
Sueldo DOUBLE NOT NULL
);  